FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /Compressor

COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .


RUN python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn", "Compressor.wsgi:application", "--bind", "62.113.44.217:8000"]
